### ISSUE TITLE
Format des cubes en entrée du Forward ou sortie de l'Adjoint

### ISSUE THREAD

**Issue by NicolasMonnier** [sidiso/surfh#14]
Actuellement en le cube généré par l'opérateur adjoint est de la taille (Lamda, alpha, beta).
Si on le modèle est défini pour plusieurs bandes de fréquence et plusieurs observations, toutes les informations seront inclues dans le même cube. 

J'avais cru comprendre qu'on aurait préféré un cube par bande de fréquence et par observation pour la reconstruction (ça équivaut à un modèle par bande et par observation). 

Il y a une raison au format actuel du cube ?  

Deuxième point, dans l'opérateur adjoint de la classe Channel, 

`l.670  out[self.wslice, ...] = self.sblur_t(blurred)`
Pour chaque bande, on vient écrire dans la zone du cube spécifique à la fréquence de de la bande.
En pratique il y a du reconvrement, donc on vient écraser les informations de la bande précédente sur le recouvrement.

(D'où l'intérêt d'avoir un cube spécifique par bande)

**Comment by forieux** [comment]
Le cube généré par l'adjoint correspond au cube que l'on souhaite reconstruire, qui est justement unique pour faire la fusion, donc c'est normal.

On souhaite plusieurs cube pour les mesures, soit l'input de l'adjoint.

> l.670  out[self.wslice, ...] = self.sblur_t(blurred)
> Pour chaque bande, on vient écrire dans la zone du cube spécifique à la fréquence de de la bande.
> En pratique il y a du reconvrement, donc on vient écraser les informations de la bande précédente sur le recouvrement.

C'est peut être une erreur, il faut que les contributions de chaque sous-bande x observation s'ajoute dans le cube de sortie de l'adjoint. Aux longueurs d'ondes communes il y a addition.

**Comment by NicolasMonnier** [comment]
> Le cube généré par l'adjoint correspond au cube que l'on souhaite reconstruire, qui est justement unique pour faire la fusion, donc c'est normal.

Oui je vois très bien l'idée. Ca me parrait juste bizarre quand j'y réfléchis car le cumul d'information sur une petite bande du spectre ne parrait pas naturel. Il faut qu'on revoit ça avec Dan car ce n'était pas clair pour lui non plus.

**Comment by forieux** [comment]
Duplication dans le forward, sommation dans le transpose

NicolasMonnier ***@***.***> writes:

>> Le cube généré par l'adjoint correspond au cube que l'on souhaite reconstruire, qui est justement unique pour faire la fusion, donc c'est normal.
>
> Oui je vois très bien l'idée. Ca me parrait juste bizarre quand j'y réfléchis car le cumul d'information sur une petite bande du spectre ne parrait pas naturel. Il faut qu'on revoit ça avec Dan car ce n'était pas clair pour lui non plus.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/sidiso/surfh/issues/14#issuecomment-1903995942
> You are receiving this because you were assigned.
>
> Message ID: ***@***.***>

-- 
+33 1 75 31 70 55
http://pro.orieux.fr

**Comment by NicolasMonnier** [comment]
> Duplication dans le forward, somme dans le transpose

C'est vrai j'avais plus la vision matricielle du problème en tête. Merci de pour l'éclairage !
